### ISSUE TITLE
"fn string" is unsafe

### ISSUE THREAD

**Issue by gengteng** [wandercn/gostd#17]
`pub fn string(b: &[u8]) -> String` 这个函数是不安全的，要么把它定义为 unsafe 的，要么请让它返回一个 `Result<String, E>`，比如在那个 &[u8] 不是 utf8 编码时返回错误，Safe Rust 中没有 Go 那种打印出来可能会有乱码的字符串，String 必须是合法的 utf8。

```go
//  据我所知这在 Safe Rust 中是做不到的
b := []byte{255, 255, 255}
fmt.Println(string(b)) // 乱码
```

原生类型重定义、公共方法首字母大写、用&str做错误返回我也很想吐槽，毕竟这是翻译不是抄一遍，建议还是按照 Rust 而不是 Go 的哲学和规范来吧。

或者至少正确性和安全性上不要打折吧，否则 Go 翻译成 Rust 的意义是什么呢？

**Comment by wandercn** [comment]
go中的string()函数是允许错误字节序列，只是会显示成“�“ ，我只是保持了这种习惯。一般情况，都是把字符串转换成[]byte来提高处理效率。

```rust
use gostd_builtin::*;
fn main() {
    let s = "hello, 世界";
    let b = s.as_bytes();
    println!("[]byte: {:?}", b);

    let c: [u8; 13] = [
        104, 101, 108, 108, 111, 44, 32, 228, 184, 150, 231, 149, 140,
    ];

    println!("{}", string(b));
    println!("{}", string(&c));
}
```
output:

```
[]byte: [104, 101, 108, 108, 111, 44, 32, 228, 184, 150, 231, 149, 140]
hello, 世界
hello, 世界
```

```go

package main

import (
	"fmt"
)

func main() {
	b := "hello, 世界"
	fmt.Println([]byte(b))
	fmt.Println(string([]byte(b)))

}

```
output:
```
[104 101 108 108 111 44 32 228 184 150 231 149 140]
hello, 世界 
```

**Comment by umaYnit** [comment]
那就不该返回rust的String类型，rust的String要求严格点utf8，否则会有内存安全隐患

**Comment by gengteng** [comment]
> go中的string()函数是允许错误字节序列，只是会显示成“�“ ，我只是保持了这种习惯。一般情况，都是把字符串转换成[]byte来提高处理效率。
> 
> ```rust
> use gostd_builtin::*;
> fn main() {
>     let s = "hello, 世界";
>     let b = s.as_bytes();
>     println!("[]byte: {:?}", b);
> 
>     let c: [u8; 13] = [
>         104, 101, 108, 108, 111, 44, 32, 228, 184, 150, 231, 149, 140,
>     ];
> 
>     println!("{}", string(b));
>     println!("{}", string(&c));
> }
> ```
> 
> output:
> 
> ```
> []byte: [104, 101, 108, 108, 111, 44, 32, 228, 184, 150, 231, 149, 140]
> hello, 世界
> hello, 世界
> ```
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> )
> 
> func main() {
> 	b := "hello, 世界"
> 	fmt.Println([]byte(b))
> 	fmt.Println(string([]byte(b)))
> 
> }
> ```
> 
> output:
> 
> ```
> [104 101 108 108 111 44 32 228 184 150 231 149 140]
> hello, 世界 
> ```

你举的这个例子里，b数组的来源就是一个合法的String，所以看上下文是能保证安全的，直接使用 from_utf8_unchecked 是没有问题的。但是你这个string函数是封装为一个 pub 的通用函数的，如果你一定需要一个约束宽松的 Go 式的字符串（conventionally but not necessarily representing UTF-8-encoded text），那你需要的确实就是 README.md 里说的自定义 GoString 了，建议还是用 Vec<u8> 封装一个吧，这样把 unsafe 强行封装为 safe 就违背了 Rust 的安全保证了。

**Comment by wandercn** [comment]
下一个版本我把这个改掉。
