### ISSUE TITLE
gostd/time报错，需要修复一下！

### ISSUE THREAD

**Issue by zhangwuqiao** [wandercn/gostd#59]
![图片](https://github.com/wandercn/gostd/assets/38390225/09c5c684-8ac3-452c-9552-2175c1491c17)

**Comment by zhangwuqiao** [comment]
The compilation environment is Windows

**Comment by wandercn** [comment]
原来没有适配windows，已经加上了，还有3个函数测试代码没过。大部分函数都没问题。明天继续fixbug

**Comment by wandercn** [comment]
@zhangwuqiao   在windows平台编译的问题已经修复

**Comment by wandercn** [comment]
@zhangwuqiao  其他依赖环境问题请看https://github.com/wandercn/gostd/issues/61
